# Generated by Django 5.0.6 on 2024-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="daywiseprediction",
            name="day4_rainfall",
            field=models.FloatField(default=0),
        ),
    ]
