# Generated by Django 5.0.6 on 2024-06-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="daywiseprediction",
            name="day1_rainfall",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="daywiseprediction",
            name="day2_rainfall",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="daywiseprediction",
            name="day3_rainfall",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="daywiseprediction",
            name="day4_rainfall",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="daywiseprediction",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="awsstations.awsstation",
            ),
        ),
        migrations.AddField(
            model_name="daywiseprediction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="daywiseprediction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
