# Generated by Django 5.0.6 on 2024-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awsstations", "0002_daywiseprediction_day1_rainfall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daywiseprediction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
