# Generated by Django 5.0.6 on 2024-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowdsource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tweet_text", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField()),
                ("sentiment", models.BooleanField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField()),
            ],
        ),
    ]
